# ask for user input and save to variables
name = input("Enter your first and last name: ")
hobby = input("Enter a favorite hobby: ")
adjective = input("Enter an adjective: ")
love = input("Enter something you love: ")
hate = input("Enter something you hate: ")
personalityTrait1 = input("Enter a personality trait: ")
personalityTrait2 = input("Enter another personality trait: ")
philosophy = input("Enter a philosophy: ")
feeling = input("Enter a feeling: ")
